name: Update Contribution Calendar

on:
  schedule:
    - cron: "0 0 * * *" # every day at midnight UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Generate calendar SVG
        run: node scripts/generateCalendar.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push updated SVG
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add assets/contributions.svg
          git commit -m "Update contribution calendar" || echo "No changes"
          git push
